operator:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    node-role.kubernetes.io/master: ""
  nameOverride: ""
  fullnameOverride: ""
  resourcePrefix: "openshift.io"
  enableAdmissionController: false
  cniBinPath: "/opt/cni/bin"
  clusterType: "kubernetes"

# Image URIs for sriov-network-operator components
images:
  operator: quay.io/openshift/origin-sriov-network-operator
  sriovConfigDaemon: quay.io/openshift/origin-sriov-network-config-daemon
  sriovCni: quay.io/openshift/origin-sriov-cni
  ibSriovCni: quay.io/openshift/origin-sriov-infiniband-cni
  sriovDevicePlugin: quay.io/openshift/origin-sriov-network-device-plugin
  resourcesInjector: quay.io/openshift/origin-sriov-dp-admission-controller
  webhook: quay.io/openshift/origin-sriov-network-webhook
