apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: sriov-network-config-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sriov-network-config-daemon
subjects:
- kind: ServiceAccount
  name: sriov-network-config-daemon
