apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriov-network-operator
roleRef:
  kind: ClusterRole
  name: sriov-network-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: openshift-sriov-network-operator
  name: sriov-network-operator

