kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-network-config-daemon
subjects:
- kind: ServiceAccount
  name: sriov-network-config-daemon
roleRef:
  kind: Role
  name: sriov-network-config-daemon
  apiGroup: rbac.authorization.k8s.io
