mode: 0755
overwrite: true
path: "/usr/local/bin/switchdev-configuration-after-NM.sh"
contents:
  inline: |
    #!/bin/bash
    set -eux
    input="/etc/sriov_config.json"

    if [ ! -f $input ]; then
      echo "File /etc/sriov_config.json not exist."
      exit
    fi

    # Required for NetworkManager configuration(e.g. bond) to settle down
    sleep 3

    jq -c '.interfaces[]' $input | while read iface;
    do
      eswitch_mode=$(echo $iface | jq '.eSwitchMode' -r)
      if [[ "$eswitch_mode" == "switchdev" ]]; then
        pci_addr=$(echo $iface | jq '.pciAddress' -r)
        name=$(echo $iface | jq '.name' -r)

        echo "load VF driver for $pci_addr"
        VfDirs=$(ls /sys/bus/pci/devices/${pci_addr} | grep virtfn)

        # load VF driver
        for VfDir in $VfDirs
        do
          VfPciAddr=$(basename "$( readlink -f /sys/bus/pci/devices/${pci_addr}/$VfDir )")
          echo $VfPciAddr > /sys/bus/pci/drivers_probe
        done
      fi
    done
