name: "Merge on lgtm label"
on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  execute:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.2
        with:
          jobs: 'lgtm'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: 'squash'
